# Generated by Django 6.0.2 on 2026-02-10 23:50

import django.contrib.postgres.fields
import django.contrib.postgres.indexes
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GuestSession',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_accessed', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField()),
            ],
            options={
                'db_table': 'guest_session',
                'indexes': [models.Index(fields=['expires_at'], name='idx_guest_session_expires_at')],
            },
        ),
        migrations.CreateModel(
            name='Measurement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('uploaded', 'Uploaded'), ('processing', 'Processing'), ('complete', 'Complete'), ('error', 'Error')], default='uploaded', max_length=20)),
                ('image_url', models.TextField()),
                ('image_width_px', models.IntegerField(blank=True, null=True)),
                ('image_height_px', models.IntegerField(blank=True, null=True)),
                ('length_in', models.DecimalField(blank=True, decimal_places=3, max_digits=6, null=True)),
                ('width_in', models.DecimalField(blank=True, decimal_places=3, max_digits=6, null=True)),
                ('area_sq_in', models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True)),
                ('perimeter_in', models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True)),
                ('paper_type', models.CharField(blank=True, choices=[('letter', 'Letter'), ('a4', 'A4')], max_length=10, null=True)),
                ('confidence', models.DecimalField(blank=True, decimal_places=3, max_digits=4, null=True)),
                ('algorithm_version', models.TextField(blank=True, null=True)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('guest_session', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='measurements', to='backend.guestsession')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='measurements', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'measurement',
            },
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('display_name', models.TextField(blank=True, null=True)),
                ('avatar_url', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'profile',
            },
        ),
        migrations.CreateModel(
            name='Shoe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand', models.TextField()),
                ('model', models.TextField()),
                ('gender', models.CharField(choices=[('women', 'Women'), ('men', 'Men'), ('unisex', 'Unisex'), ('kids', 'Kids'), ('unknown', 'Unknown')], default='unknown', max_length=10)),
                ('function_tags', django.contrib.postgres.fields.ArrayField(base_field=models.TextField(), blank=True, default=list)),
                ('style_tags', django.contrib.postgres.fields.ArrayField(base_field=models.TextField(), blank=True, default=list)),
                ('attributes_json', models.JSONField(blank=True, default=dict)),
                ('insole_length_in', models.DecimalField(blank=True, decimal_places=3, max_digits=6, null=True)),
                ('insole_width_in', models.DecimalField(blank=True, decimal_places=3, max_digits=6, null=True)),
                ('insole_area_sq_in', models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True)),
                ('insole_perimeter_in', models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True)),
                ('shoe_image_url', models.TextField(blank=True, null=True)),
                ('product_url', models.TextField(blank=True, null=True)),
                ('price_usd', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'shoe',
                'indexes': [models.Index(fields=['brand', 'model'], name='idx_shoe_brand_model'), django.contrib.postgres.indexes.GinIndex(fields=['function_tags'], name='idx_shoe_tags_gin_function'), django.contrib.postgres.indexes.GinIndex(fields=['style_tags'], name='idx_shoe_tags_gin_style')],
            },
        ),
        migrations.CreateModel(
            name='Recommendation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('run_id', models.UUIDField()),
                ('rank', models.IntegerField()),
                ('score', models.DecimalField(blank=True, decimal_places=6, max_digits=10, null=True)),
                ('algorithm_version', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('measurement', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recommendations', to='backend.measurement')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recommendations', to=settings.AUTH_USER_MODEL)),
                ('shoe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recommendations', to='backend.shoe')),
            ],
            options={
                'db_table': 'recommendation',
            },
        ),
        migrations.CreateModel(
            name='ShoeSize',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('us_size', models.DecimalField(decimal_places=1, max_digits=4)),
                ('width', models.CharField(choices=[('narrow', 'Narrow'), ('regular', 'Regular'), ('wide', 'Wide'), ('extra_wide', 'Extra Wide')], default='regular', max_length=12)),
                ('is_available', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('shoe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sizes', to='backend.shoe')),
            ],
            options={
                'db_table': 'shoe_size',
            },
        ),
        migrations.CreateModel(
            name='TrainingImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_url', models.TextField()),
                ('label_json', models.JSONField(blank=True, default=dict)),
                ('in_dataset', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='training_images', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'training_image',
            },
        ),
        migrations.CreateModel(
            name='UserCollection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('wishlist', 'Wishlist'), ('owned', 'Owned')], max_length=10)),
                ('size', models.TextField(blank=True, null=True)),
                ('color', models.TextField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('shoe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='collections', to='backend.shoe')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='collections', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'user_collection',
            },
        ),
        migrations.AddIndex(
            model_name='measurement',
            index=models.Index(fields=['user', '-created_at'], name='idx_measurement_user_created'),
        ),
        migrations.AddIndex(
            model_name='measurement',
            index=models.Index(fields=['guest_session', '-created_at'], name='idx_measurement_guest_created'),
        ),
        migrations.AddIndex(
            model_name='measurement',
            index=models.Index(fields=['status'], name='idx_measurement_status'),
        ),
        migrations.AddConstraint(
            model_name='measurement',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('user__isnull', False), ('guest_session__isnull', True)), models.Q(('user__isnull', True), ('guest_session__isnull', False)), _connector='OR'), name='chk_measurement_owner'),
        ),
        migrations.AddConstraint(
            model_name='measurement',
            constraint=models.CheckConstraint(condition=models.Q(('length_in__isnull', True), ('length_in__gt', 0), _connector='OR'), name='chk_measurement_length_positive'),
        ),
        migrations.AddConstraint(
            model_name='measurement',
            constraint=models.CheckConstraint(condition=models.Q(('width_in__isnull', True), ('width_in__gt', 0), _connector='OR'), name='chk_measurement_width_positive'),
        ),
        migrations.AddConstraint(
            model_name='measurement',
            constraint=models.CheckConstraint(condition=models.Q(('area_sq_in__isnull', True), ('area_sq_in__gt', 0), _connector='OR'), name='chk_measurement_area_positive'),
        ),
        migrations.AddConstraint(
            model_name='measurement',
            constraint=models.CheckConstraint(condition=models.Q(('perimeter_in__isnull', True), ('perimeter_in__gt', 0), _connector='OR'), name='chk_measurement_perimeter_positive'),
        ),
        migrations.AddIndex(
            model_name='recommendation',
            index=models.Index(fields=['user', '-created_at'], name='idx_reco_user_created'),
        ),
        migrations.AddIndex(
            model_name='recommendation',
            index=models.Index(fields=['user', 'shoe'], name='idx_reco_user_shoe'),
        ),
        migrations.AddIndex(
            model_name='recommendation',
            index=models.Index(fields=['user', 'run_id', 'rank'], name='idx_reco_user_run_rank'),
        ),
        migrations.AddConstraint(
            model_name='recommendation',
            constraint=models.CheckConstraint(condition=models.Q(('rank__gt', 0)), name='chk_recommendation_rank_positive'),
        ),
        migrations.AddConstraint(
            model_name='recommendation',
            constraint=models.UniqueConstraint(fields=('user', 'run_id', 'rank'), name='recommendation_user_id_run_id_rank_key'),
        ),
        migrations.AddIndex(
            model_name='shoesize',
            index=models.Index(fields=['shoe', 'us_size', 'width', 'is_available'], name='idx_shoe_size_lookup'),
        ),
        migrations.AddConstraint(
            model_name='shoesize',
            constraint=models.UniqueConstraint(fields=('shoe', 'us_size', 'width'), name='shoe_size_shoe_id_us_size_width_key'),
        ),
        migrations.AddIndex(
            model_name='trainingimage',
            index=models.Index(fields=['in_dataset'], name='idx_training_in_dataset'),
        ),
        migrations.AddIndex(
            model_name='trainingimage',
            index=models.Index(fields=['user', '-created_at'], name='idx_training_user_created'),
        ),
        migrations.AddIndex(
            model_name='usercollection',
            index=models.Index(fields=['user', 'type', '-created_at'], name='idx_coll_user_type_created'),
        ),
        migrations.AddConstraint(
            model_name='usercollection',
            constraint=models.UniqueConstraint(fields=('user', 'shoe', 'type'), name='user_collection_user_id_shoe_id_type_key'),
        ),
    ]
