# Generated by Django 6.0.2 on 2026-04-24 06:11

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0002_auth_user_email_index'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserFeedback',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('shoe_profile', models.CharField(max_length=255)),
                ('feedback_type', models.CharField(choices=[('too_narrow', 'Too Narrow'), ('too_wide', 'Too Wide'), ('too_short', 'Too Short'), ('too_long', 'Too Long'), ('perfect', 'Perfect')], max_length=20)),
                ('current_tolerances', models.JSONField()),
                ('fit_score', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True)),
                ('measurements', models.JSONField(blank=True, null=True)),
                ('severity_rating', models.IntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'user_feedback',
                'indexes': [models.Index(fields=['shoe_profile'], name='idx_feedback_shoe_profile'), models.Index(fields=['created_at'], name='idx_feedback_created_at'), models.Index(fields=['feedback_type'], name='idx_feedback_type')],
            },
        ),
    ]
