# Generated by Django 6.0.2 on 2026-05-07 06:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0010_measurement_method'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shoecolorway',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='shoecolorwaysize',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.CreateModel(
            name='ToleranceHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tolerances', models.JSONField()),
                ('total_feedback_count', models.IntegerField(default=0)),
                ('active', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_feedback_timestamp', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'tolerances',
                'indexes': [models.Index(fields=['active', '-created_at'], name='idx_tolerance_active_created'), models.Index(fields=['last_feedback_timestamp'], name='idx_tolerance_last_feedback')],
            },
        ),
    ]
