# Generated by Django 6.0.2 on 2026-05-13 05:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0011_alter_shoecolorway_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='shoecolorway',
            name='dominant_color_computed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='shoecolorway',
            name='dominant_color_hex',
            field=models.CharField(blank=True, max_length=7, null=True),
        ),
        migrations.AddField(
            model_name='shoecolorway',
            name='dominant_color_source_url',
            field=models.TextField(blank=True, null=True),
        ),
    ]
