# Generated by Django 6.0.2 on 2026-05-13 20:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0012_shoecolorway_dominant_color'),
    ]

    operations = [
        migrations.AddField(
            model_name='shoecolorway',
            name='color_palette_hex',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
